name: Keep API Alive

on:
  schedule:
    # A cada 10 minutos
    - cron: '*/10 * * * *'

jobs:
  ping-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Enviar requisição para a API
        run: |
          python -c "import requests; requests.get('https://api-data-hora-python.onrender.com/data-hora', timeout=10); print('API pingada com sucesso!');"